services:
  polyscope:
    image: universalrobots/ursim_e-series:5.15.0 # https://hub.docker.com/r/universalrobots/ursim_e-series
    ports:
      - "29999:29999"
      - "30001:30001"
      - "30002:30002"
      - "30003:30003"
      - "30004:30004"
      - "30020:30020"
      - "5900:5900"
      - "6080:6080"
    volumes:
      - type: bind
        source: ./urprograms
        target: /ursim/programs
    tty: true
    stdin_open: true
  proxy:
    build:
      context: ./python
      dockerfile: Dockerfile
    ports:
      - "8767:8767"
      - "8000:8000"
    volumes:
      - type: bind
        source: ./python
        target: /app
    tty: true
    stdin_open: true
    environment:
      - ROBOT_IP=polyscope
      - ROBOT_FEEDBACK_PORT=8000
      - ROBOT_FEEDBACK_HOST=proxy
    profiles:
        - ""
  test:
    command: ["python", "test.py"]
    profiles: ["test"]
    build:
      context: ./python
      dockerfile: Dockerfile
    ports:
      - "8767:8767"
      - "8000:8000"
    volumes:
      - type: bind
        source: ./python
        target: /app
    tty: true
    stdin_open: true
#https://github.com/urrsk/ursim_docker/blob/main/ursim/e-series/Dockerfile
# To run test container, proxy has to be not running. Then run `docker compose up test -d` or `docker compose --profile test up -d`

