services:
  polyscope:
    image: universalrobots/ursim_e-series:5.15.0 # https://hub.docker.com/r/universalrobots/ursim_e-series
    ports:
      - "30001:30001"
      - "30002:30002"
      - "30003:30003"
      - "30004:30004"
      - "5900:5900"
      - "6080:6080"
    volumes:
      - type: bind
        source: ./urprograms
        target: /ursim/programs
    tty: true
    stdin_open: true

#https://github.com/urrsk/ursim_docker/blob/main/ursim/e-series/Dockerfile