services:
  polyscope:
    build:
      dockerfile: Dockerfile
    #    image: universalrobots/ursim_e-series:5.15 # https://hub.docker.com/r/universalrobots/ursim_e-series
    ports:
      - "29999:29999"
      - "30001:30001"
      - "30002:30002"
      - "30003:30003"
      - "30004:30004"
      - "30020:30020"
      - "5900:5900"
      - "6080:6080"
      - "2222:22"
    volumes:
      - type: bind
        source: ./urprograms
        target: /ursim/programs
    tty: true
    stdin_open: true
  proxy:
    build:
      context: ./python
      dockerfile: Dockerfile
    ports:
      - "8767:8767"
      - "8000:8000"
    volumes:
      - type: bind
        source: ./python
        target: /app
    tty: true
    stdin_open: true
    environment:
      - ROBOT_IP=polyscope
      - ROBOT_FEEDBACK_PORT=8000
      - ROBOT_FEEDBACK_HOST=proxy
      - SSH_USERNAME=root
    profiles:
        - ""
  